export const Endpoints = {
  sign_up: "/auth/signup",
  login: "/auth/login",
  logout: "/auth/logout",
  getUserLogedData: "/auth/zuku",
  postUpload: "/post/upload",
  postCreate: "/post/create",
  GetPosts: "/post/all-posts",
  GetMyPosts: "/post/my-posts",
  deletePost: (postId) => `/post/delete/${postId}`,
  viewPost: (postId) => `/post/view/${postId}`,
  updatePost: (postId) => `/post/update/${postId}`,
  LikePost: (postId) => `/post/like/${postId}`,
  UnLikePost: (postId) => `/post/unlike/${postId}`,
  CreateComment: (postId) => `/comment/create/${postId}`,
  GetCommentsByPostId: (postId) => `/comment/${postId}`,
  DeleteComment: (commentId) => `/comment/${commentId}`,
  UpdateProfile: "/user/profile",
};
