export const Endpoints = {
  sign_up: "/auth/signup",
  login: "/auth/login",
  logout: "/auth/logout",
  getUserLogedData: "/auth/user/me",
  postUpload: "/post/upload",
  postCreate: "/post/create",
  GetPosts: "/post/allposts",
  GetMyPosts: "/post/myposts",
  GetAllUsers: "/auth/allusers",
  GetAllFollowers: "/auth/user/followers",
  GetAllFollowings: "/auth/user/followings",
  Followuser: (userId) => `/auth/user/follow/${userId}`,
  UnFollowuser: (userId) => `/auth/user/unfollow/${userId}`,
  deletePost: (postId) => `/post/delete/post/${postId}`,
  viewPost: (postId) => `/post/view/${postId}`,
  updatePost: (postId) => `/post/edit/${postId}`,
  LikePost: (postId) => `/post/like/${postId}`,
  UnLikePost: (postId) => `/post/dislike/${postId}`,
  CreateComment: (postId) => `/comment/create/${postId}`,
  GetCommentsByPostId: (postId) => `/comment/${postId}`,
  DeleteComment: (commentId) => `/comment/delete/${commentId}`,
  UpdateProfile: "auth/user/profile",
};
